### PR TITLE
Minecraft Forge 1.9 migration

### PR DESCRIPTION
**Pull request by jerr**
Hi Minecraft moders,

In our next Devoxx4Kids session in Montreal, we will use Minecraft 1.9 version.
So we updated the workshop with the most recent version of Minecraft Forge.

Hope this helps for other Devoxx4Kids

Regards,
Jérémie (Devoxx4Kids Quebec at Montreal)

### CODE REVIEW

**Comment by arun-gupta** [comment]
@jerr The source code was updated by @AdityaGupta1 a couple of days ago already. And that's why this merge request shows conflict. Can you please check?

**Comment by jerr** [comment]
@arun-gupta  ok no problem I will look at it.

Regards,
Jérémie

**Comment by AdityaGupta1** [comment]
I'm going to close the pull request now because everything has already been updated to 1.9, but thanks for the pull request because it gave me an idea about how to fix the Fast Bows mod (see https://github.com/devoxx4kids/materials/commit/1d492f54414984e6977a8019ec568204f57c61f2).

**Comment by jerr** [comment]
Hi @AdityaGupta1 

I merged the code with yours. I used an older 1.9 version than you so I kept your code in priority.

I fixed a couple of inconsistency with the doc and the setup of the mod with the addition of mcmod.info file.
But overall it looks ok.

Regards,
Jérémie.

**Pull request closed without merging**
