### PR TITLE
Android workshop01

### PR DESCRIPTION
**Pull request by laorine**
Hello, 

I would like to share with you my Android workshop given during the Montreal Devoxx4kids last weekend.
It was an amazing experience for me and appreciated by the attendees.
This is a first version, I have a lot of ideas to improve it, but it's for the next session;)

Do not hesitate to tell me if I need to change somethings.

Regards,
Laorine.

### CODE REVIEW

**Comment by daniel-deluca** [comment]
Hi Laorine
Thank you so much to share your work. Greatly appreciated.
Could you please add an intermediary folder that will indicate the workshop spoken language:
workshops/android/en/XXXXXXX  instead of workshops/android/XXXXXXX

Many thanks in advance
Cheers
Daniel

**Comment by laorine** [comment]
Hi Daniel,
I do it for the workshop 1. Tell me if it is okay for you. 
I'll add french version next time with more explications for both languages.

Thanks for the review, 
Laorine.

**Comment by daniel-deluca** [comment]
Hi Laorine,
Yes, please take your time..
I'll then merge your changes.
Cheers and thanks again for sharing your work
Daniel

**Comment by laorine** [comment]
Hi Daniel,
I add the french translation. I will do more for the next devoxx4kids Montreal session. If it is okay for you, you can validate this pull request. 

Thank you again for your time,
Laorine.

**Pull request merged**
